
# Numpy functions that will make your life easier!


I've attached 5 numpy functions below. These functions will be handy in all sorts of ways in your coding journey. They vary from whether you want to stack different array columns together or determine if there are digits in your array. Read on to learn how they function!
Write a short introduction about Numpy and list the chosen functions. 

- np.column_stack
- np.flip
- np.matlib.empty
- np.matlib.eye
- np.matlib.rand


In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "zaneyhuss/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/zaneyhuss/numpy-array-operations


'https://jovian.ai/zaneyhuss/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [120]:
# List of functions explained 
function1 = np.column_stack
function2 = np.flip
function3 = np.matlib.empty
function4 = np.matlib.eye
function5 = np.matlib.rand

## Function 1 - np.column_stack

This function will help you stack 1-D arrays into a column that will tranform it into a 2-D array.

In [41]:
# Example 1 - working 

a = ((1, 2, 3),
    (6, 3, 5))

b = ((5, 6, 7),
    (2, 5, 7))

np.column_stack((a, b))

array([[1, 2, 3, 5, 6, 7],
       [6, 3, 5, 2, 5, 7]])

Example 1 shows the function stacking 2 different 2-D arrays into a single 2-D array

In [42]:
# Example 2 - working

A = ((10, 20, 30))

B = ((102, 47, 32))

np.column_stack((B, A))

array([[102,  10],
       [ 47,  20],
       [ 32,  30]])

Example 2 shows 2 1-D arrays stacking columns and forming a 3-D array

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = ((1, 2, 
        3, 4))

arr2 = ((5, 6, 7))

np.column_stack((arr1, arr2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

Reason for error:
For the function to perform, the columns must be 1-D arrays. The example above has uneven arrays. To fix this error, simply match up the arrays and have them both be either 1-D or 2-D.

This function is similar to np.concatenate

In [ ]:
jovian.commit()

## Function 2 - Np.flip

This function will flip the order of variables in an array along which given axis.

In [51]:
# Example 1 - working

arr1 = np.array([
    [[11, 12, 13],
    [13, 15, 16]],
    [[17, 18, 19],
    [20, 21, 22]]])

np.flip(arr1, 0)

array([[[17, 18, 19],
        [20, 21, 22]],

       [[11, 12, 13],
        [13, 15, 16]]])

Example 1 shows the function flipping the array on the axis=2. The variables stayed in the same rows just flipped their order

In [47]:
# Example 2 - working
arr1 = np.array([
    [[11, 12, 13],
    [13, 15, 16]],
    [[17, 18, 19],
    [20, 21, 22]]])

np.flip(arr1, -2)

array([[[13, 15, 16],
        [11, 12, 13]],

       [[20, 21, 22],
        [17, 18, 19]]])

Example 2 shows the function flipping on a -2 axis. This caused the columns and the rows to flip

In [52]:
# Example 3 - breaking (to illustrate when it breaks)
np.flip(arr1,-8 )

AxisError: axis -8 is out of bounds for array of dimension 3

Example 3 shows flipping the array on the -8 axis. This is not possible due to the array only having 3 dimensions. To fix this, stay within the dimensions

This function is great because you can rearrange the elements but the shape of the array is preserved

In [53]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "zaneyhuss/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/zaneyhuss/numpy-array-operations


'https://jovian.ai/zaneyhuss/numpy-array-operations'

## Function 3 - np.matlib.empty

This function returns a matrix that is completely random in shape and variables

In [124]:
# Example 1 - working
import numpy.matlib

np.matlib.empty((2, 8))


matrix([[4.66492322e-310, 0.00000000e+000, 2.41907520e-312,
         2.14321575e-312, 2.46151512e-312, 2.31297541e-312,
         2.35541533e-312, 2.05833592e-312],
        [2.22809558e-312, 2.56761491e-312, 2.48273508e-312,
         2.05833592e-312, 2.05833592e-312, 2.29175545e-312,
         2.07955588e-312, 2.14321575e-312]])

The function made a matrix with random data

In [126]:
# Example 2 - working
np.matlib.empty((110, 10))

matrix([[ 4.66492323e-310,  6.94744652e-310,  4.66492323e-310, ...,
          4.66492323e-310,  1.17049428e+214,  0.00000000e+000],
        [ 3.60700405e+096,  4.66492322e-310,  4.66478335e-310, ...,
          0.00000000e+000,  1.22121973e-247,  4.66492322e-310],
        [ 2.47032823e-323,  4.66492323e-310,  4.66492323e-310, ...,
          4.66492322e-310, -3.37199743e+261,  4.66492323e-310],
        ...,
        [ 0.00000000e+000,  3.21142670e-322,  4.66492322e-310, ...,
          4.66492323e-310,  7.11454530e-322,  2.37151510e-322],
        [ 4.66492319e-310,  4.66492322e-310,  1.27319747e-313, ...,
          9.88945118e-170, -5.78928434e-153,  0.00000000e+000],
        [ 0.00000000e+000,  4.00193173e-322,  4.66492321e-310, ...,
          2.12199579e-314,  8.48798317e-314,  4.66492323e-310]])

In [127]:
# Example 3 - breaking (to illustrate when it breaks)
np.matlib.empty((-2, 8))

ValueError: negative dimensions are not allowed

The function will not perform if there are negative dimensions 

Some closing comments about when to use this function.

In [128]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "zaneyhuss/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/zaneyhuss/numpy-array-operations


'https://jovian.ai/zaneyhuss/numpy-array-operations'

## Function 4 - np.matlib.eye

This function returns a matrix where 1's are diagonal and zeros are everywhere else

In [103]:
# Example 1 - working



numpy.matlib.eye(10, k=0, dtype=float)

matrix([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Example 2 shows the function where the matrix has 6 rows and the elements that are 1 are going down diagonally

In [113]:
# Example 2 - working

numpy.matlib.eye(10, k= -7, dtype=float)

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

Example 2 shows the function with a negative index, the diagonal is lower

In [118]:
# Example 3 - breaking (to illustrate when it breaks)

numpy.matlib.eye(8, k= , dtype=float)

SyntaxError: invalid syntax (3257847640.py, line 3)

The function needs a index

Some closing comments about when to use this function.

In [119]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "zaneyhuss/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/zaneyhuss/numpy-array-operations


'https://jovian.ai/zaneyhuss/numpy-array-operations'

## Function 5 - np.matlib.rand

This function returns a matrix of random values with any given shape

In [62]:
# Example 1 - working

# import matlib
import numpy.matlib
np.matlib.rand(7, 4)

matrix([[0.29371405, 0.63097612, 0.09210494, 0.43370117],
        [0.43086276, 0.4936851 , 0.42583029, 0.31226122],
        [0.42635131, 0.89338916, 0.94416002, 0.50183668],
        [0.62395295, 0.1156184 , 0.31728548, 0.41482621],
        [0.86630916, 0.25045537, 0.48303426, 0.98555979],
        [0.51948512, 0.61289453, 0.12062867, 0.8263408 ],
        [0.60306013, 0.54506801, 0.34276383, 0.30412079]])

Example 1 shows a random matrix

In [63]:
# Example 2 - working

np.matlib.rand((2, 3), 4)

matrix([[0.41702221, 0.68130077, 0.87545684],
        [0.51042234, 0.66931378, 0.58593655]])

Example 2 shows that if the first arguement is a tuple other arguments are ignored

In [70]:
# Example 3 - breaking (to illustrate when it breaks)

np.matlib.rand(1, -8)

ValueError: negative dimensions are not allowed

Example 3 shows the function but one of the arguments are negative. Negative dimensions are not allowed, change the argument to a whole number

Some closing comments about when to use this function.

In [71]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "zaneyhuss/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/zaneyhuss/numpy-array-operations


'https://jovian.ai/zaneyhuss/numpy-array-operations'

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [130]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "zaneyhuss/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/zaneyhuss/numpy-array-operations


'https://jovian.ai/zaneyhuss/numpy-array-operations'